//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationalSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeesPayed_
    {
        public int ID { get; set; }
        public Nullable<int> s_id { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Payed { get; set; }
        public Nullable<int> Remaining { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Added_by { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
    
        public virtual student_info student_info { get; set; }
    }
}
