//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationalSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_info
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Principle { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string ShortSPEL { get; set; }
        public string ShortName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Code { get; set; }
        public string Logo { get; set; }
        public string MobileToken { get; set; }
        public string Machine { get; set; }
    }
}
