//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationalSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class student_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student_info()
        {
            this.FeesDefaulter_ = new HashSet<FeesDefaulter_>();
            this.FeesPayed_ = new HashSet<FeesPayed_>();
        }
        [Key]
        public int S_id { get; set; }
        public int id { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        
        public string Gender { get; set; }
        public string Class { get; set; }
        public string ClassRoll { get; set; }
        public Nullable<System.DateTime> Date_of_admn { get; set; }
        public string Father_ocupation { get; set; }
        public Nullable<System.DateTime> Date_of_birth { get; set; }
        public string Refrence { get; set; }
        public Nullable<int> Admn_fee { get; set; }
        public Nullable<int> Monthly_dues { get; set; }
        public string Religion { get; set; }
        public string Cast { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<int> Family_id { get; set; }
        public string S_cnic { get; set; }
        public string F_cnic { get; set; }
        public Nullable<bool> status { get; set; }
        public string Simg { get; set; }
        public Nullable<System.DateTime> exit_date { get; set; }
        public string Admited_Class { get; set; }
        public string Admited_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeesDefaulter_> FeesDefaulter_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeesPayed_> FeesPayed_ { get; set; }
    }
}
